### ISSUE TITLE
Custom Samples unstable

### ISSUE THREAD

**Issue by Itaborala** [cephasteom/zen-3#1]
I want to use my own samples with the sampler instruments. I have successfully installed `ct-samples` and hosted my soundbank into a folder inside `samples`.

However, it is not every time that the sound are loaded to Zen.
Some behaviours that I got:

When there are simple refreshes, there is a conflict between loading the native sound bank and the custom one. Usually the custom bank returns a 404 error and is not loaded. sometimes, however, after a few refreshes, the opposite happened, and I had the custom bank but not the native one.

Temporary workaround: When I right-click the refresh icon in Chrome and use the `empty cache and hard reload` option, it loads all sounds (most of the times). However,  this means that any code progress is lost in the way. So, anyone reproducing this issue needs to make sure to have local backups of their own creations.

**Comment by cephasteom** [comment]
@Itaborala Thanks for logging this issue. I'll take a look and get back to you ASAP. Could you let me know what browser, device and OS you are running?

**Comment by Itaborala** [comment]
Sure: I forgot to provide this info in the last message:

OS: Linux Ubuntu Budgie 22.10 with AwesomeWM v4.3
Browser: Google Chrome Version 110.0.5481.100

**Comment by cephasteom** [comment]
Hi @Itaborala. I've updated the service-worker so that it never caches request to files served locally through `ct-samples`. This has improved stability on my machine, and I'm hoping it will on yours too. A couple of things:
- running service workers can be seen in devtools > Application > Service Workers. Having just deployed an update to Zen you should see the new service worker trying to install. This may take a while, and you may need to close and reopen your browser for it to complete the operation and for the fix to be implemented. 
- I've also updated `ct-samples` to fix the reported vulnerabilities. Pull the changes then rebuild your node_modules using `npm i`.

Let me know how you get on.
